#!/usr/bin/env bash

if [ -z "$VERSION" ]; then
    VERSION=$(node -e "console.log(require('./package.json').version)")
fi

if [ -z "$NAME" ]; then
    NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
fi

if [ -z "$NAMESPACE" ]; then
    NAMESPACE=$(node -e "var dg=require('./package.json')['docker-namespace']; console.log(dg? dg + '/' : '') ")
fi

NAME="$NAMESPACE$NAME"

echo "$VERSION"

docker build -t "$NAME:$VERSION" "$@" .
