#!/usr/bin/env bash

if [ -z "$VERSION" ]; then
    VERSION=$(node -e "console.log(require('./package.json').version)")
fi

if [ -z "$NAME" ]; then
    NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
fi

PREFIX=$(node -e "console.log(require('./package.json')['docker-registry'] || '')")
if [ -z "$PREFIX" ]; then
    PREFIX=$(node -e "console.log(require('./package.json')['docker-user'] || '')")
fi

if [ -z "$PREFIX" ]; then
    echo "docker push requires either docker-registry or docker-user in package.json"
    exit 1
fi

if [ -z "$NAMESPACE" ]; then
    NAMESPACE=$(node -e "var dg=require('./package.json')['docker-namespace']; console.log(dg? dg + '/' : '') ")
fi

NAMESPACE_NAME="$NAMESPACE$NAME"

echo "$VERSION"

docker tag "$NAMESPACE_NAME:$VERSION" "$PREFIX/$NAMESPACE_NAME"
docker push "$PREFIX/$NAMESPACE_NAME"
docker tag "$NAMESPACE_NAME:$VERSION" "$PREFIX/$NAMESPACE_NAME:$VERSION"
docker push "$PREFIX/$NAMESPACE_NAME:$VERSION"
docker tag -f "$NAMESPACE_NAME:$VERSION" "$PREFIX/$NAMESPACE_NAME:latest"
docker push "$PREFIX/$NAMESPACE_NAME:latest"
